# Generated by Django 3.2.15 on 2022-09-14 18:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('profiles', '0002_auto_20220911_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion'), ('Art', 'Art'), ('Food', 'Food'), ('Architecture', 'Architecture'), ('Adventure', 'Adventure'), ('Other', 'Other')], default='Other', max_length=15)),
                ('text_slug', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.CharField(blank=True, default='', max_length=160)),
                ('image', models.ImageField(upload_to='blog_image/%Y/%m/%d', verbose_name='Blog Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Collects profile ids as Integer', size=None)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('comments', models.ManyToManyField(blank=True, to='comments.Comment')),
            ],
        ),
    ]
